#       AUTO                  AUTO                          AUTO                       MANUAL
# Code =========> Unit Tests =========> Integration Tests =========> Acceptance Test  =========> Deploy to Staging/Production
