# See CONTRIBUTING.md for instructions.
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Commitizen runs in commit-msg stage
# but we don't want to run the other hooks on commit messages
default_stages: [commit]

# Use a slightly older version of node by default
# as the default uses a very new version of GLIBC
default_language_version:
  node: 16.18.0

repos:
  # Check formatting and lint for starlark code
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 5.1.0.2
    hooks:
      - id: buildifier
        args: &args
           - --warnings=all
      - id: buildifier-lint
        args: *args
  # Enforce that commit messages allow for later changelog generation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.18.0
    hooks:
      # Requires that commitizen is already installed
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.0"
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: ["--no-markdown-linebreak-ext"]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - push

  - repo: local
    hooks:
      - id: bazel-super-formatter
        name: Format
        language: system
        entry: bazel run @aspect_rules_format//format
        files: .*
