# Docs: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  main:
    docker:
        - image: docker.io/doevelopper/cfs-dev-tools-common:latest
jobs:
  build:
    executor: main
    environment:
    steps:
        - checkout
        - run: bazel build //...

# Orchestrate or schedule a set of jobs
workflows:
  build:
    jobs:
        - build
    docker:
        - image: docker.io/doevelopper/cfs-dev-tools-omg:0.0.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-cache
      - run: bazel test --test_output=errors //...
