# Override http_archive for local testing
local_repository(
    name = "com.github.doevelopper.rules-sdlc",
    path = "../..",
)

#---SNIP--- Below here is re-used in the workspace snippet published on releases

######################
# rules_infra setup #
######################
# Fetches the rules_infra dependencies.
# If you want to have a different version of some dependency,
# you should fetch it *before* calling this.
# Alternatively, you can skip calling this function, so long as you've
# already fetched all the dependencies.
load("@com.github.doevelopper.rules-sdlc//src/main/resources/starlark/rules:repositories.bzl", "rules_infra_register_dependencies")
rules_infra_register_dependencies()
