#ifndef COM_GITHUB_DOEVELOPPER_RULES_SDLC_SEMVER_GITREVISION_HPP
#define COM_GITHUB_DOEVELOPPER_RULES_SDLC_SEMVER_GITREVISION_HPP

#define API_LIB_NAME_STR           "RULES_SDLC"
#define API_LIB_VERSION_STR        "0.0.1"
#define API_LIB_DESCRIPTION_STR    "Bazel Rules sdlc for my projects "
#define API_LIB_COPYRIGHT_STR      "(C) 2012 - 2023 acme Ltd"
#define API_LIB_COPYRIGHT_FULL_STR "Copyright (C) 2012 - 2023 acme Ltd"

#define API_LIB_PROJECT_STR         "Rule Infra"
#define API_LIB_PACKAGE_STR         "Bazel Rules Infra"
#define API_LIB_AUTHOR_STR          "AHL <rolland.doeADgmail.com>"
#define API_LIB_RELEASE_ISODATE_STR "2012-05-23T15:17:49+00:00"
#define API_LIB_RELEASE_YEAR_STR    "2012"
#define API_LIB_RELEASE_DATE_STR    "2012-05-23"
#define API_LIB_RELEASE_TIME_STR    "15:17:49"
#define API_LIB_FULL_REVISION_STR   "0.0.1"
#define API_LIB_REVISION_STR        "0.0.1"

#define API_LIB_RELEASE_YEAR       2012
#define API_LIB_RELEASE_EPOCH_TIME 1337786269
#define API_LIB_MAJOR_REVISION     1
#define API_LIB_MINOR_REVISION     6
#define API_LIB_PATCHLEVEL         1

#endif
