name: Greetings

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    name: Greeting
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: >
          'Hello @${{ github.actor }}, thanks for adding your first pull request to rules-sdlc. If you have questions, please do not hesitate to contact us.'
          **PS:** _I'm just an automated script, not a human being._
        issue-message: >
          Thanks for adding your first issue to rules-sdlc. If you have questions, please do not hesitate to contact us. Please remember to reference [Contributing.md](https://github.com/doevelopper/rules-sdlc/blob/master/Contributing.md)
          If you are a developer then it is advised to go through the [Developer Training Guide](https://github.com/constellation-app/constellation-training).
          **PS:** _I'm just an automated script, not a human being._
